#server:
#  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Product Service Route
        - id: product-service-get
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product
        - id: product-service-post-add
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/add
        # Order Service Route
        - id: order-service-post
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/add

