spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
  cloud:
    gateway:
      routes:
        # Product Service get Route
        - id: product-service-get
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product
        # Product Service post Route
        - id: product-service-post-add
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/add
        # Order Service Route
        - id: order-service-post
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/add
        # Discovery Server Route
        - id: discovery-server
          uri: http://eureka:password@${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # Discovery Server Static Route
        - id: discovery-server-static-resources
          uri: http://eureka:password@${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
app:
  eureka-server: localhost