# API-GATEWAY
server:
  port: 8181
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservices-realm
  cloud:
    gateway:
      routes:
        # Discovery Server Route
        - id: discovery-server
          uri: http://eureka:password@${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # Discovery Server Static Route
        - id: discovery-server-static-resources
          uri: http://eureka:password@${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**
        ##############################################################################
        # Customer Service - ogólna obsługa
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/**
#        ##############################################################################
        # product Service - ogólna obsługa
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        ##############################################################################
        # order Service - ogólna obsługa
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        ##############################################################################
        # inventory Service - ogólna obsługa
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
        ##############################################################################
        # fraud Service - ogólna obsługa
        - id: fraud-service
          uri: lb://fraud-service
          predicates:
            - Path=/api/v1/fraud/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

app:
  eureka-server: localhost

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      sampling:
        probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"