server:
  port: 8084

spring:
  application:
    name: product-service
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://bgnat:password@localhost:27017/dbname?authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka