server:
  port: 0

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://bgnat:password@localhost:27017/product?authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      sampling:
        probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"