# Product-Service
spring:
  data:
    mongodb:
      uri: mongodb://bgnat:password@mongo-product:27017/product?authSource=admin

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
